import type { Metadata } from "next";
import { Inter, Noto_Serif_Lao} from "next/font/google";
import "./globals.css"
import Header from "./components/header";
import Footer from "./components/footer";


const inter = Inter({
  subsets: ["latin"],
});

const noto = Noto_Serif_Lao({
  subsets: ["lao"]
});


export const metadata: Metadata = {
  title: "xeng_tech.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 <body className={`${inter.className} ${noto.className} antialiased`}>
  <Header/>
  {children}
  <Footer/>










  </body>
    </html>
  );
}
